# Generated by Django 3.1.6 on 2021-06-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_user_name', models.CharField(default='NULL22', max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
